/**
 * Product Seed Script — BuildMore InfraMart Backend
 * Run: node scripts/seedProducts.js
 *
 * Upserts 10+ products per category for all 14 platform categories.
 * Safe to re-run — existing products (matched by name) are updated.
 */

const mongoose = require('mongoose');
require('dotenv').config({
    path: process.env.NODE_ENV === 'production' ? '.env.production' : '.env.local'
});

const Category = require('../models/CategoryModel');
const Product  = require('../models/ProductModel');

// ─────────────────────────────────────────────
// PRODUCTS — keyed by category name
// ─────────────────────────────────────────────

const PRODUCTS_BY_CATEGORY = {

    'Cement & Concrete': [
        {
            productName: 'UltraTech OPC 53 Grade Cement (50 kg)',
            desc: 'Ordinary Portland Cement for high-strength concrete, industrial flooring, and bridge construction. Consistent quality with rapid strength gain.',
            subcategory: 'Cement',
            price: 390, originalPrice: 430,
            materialSpecifications: 'Grade: 53 | Standard: IS 12269:2013 | Initial Set: 30 min | 28-day Strength: 53 MPa',
            stock: 10000, tier: 'Bulk Distribution', bulkInfo: 'Pallet: 50 bags. Truck load discount on 20+ pallets.', rating: 4.6, reviews: 320,
        },
        {
            productName: 'ACC PPC Blended Cement (50 kg)',
            desc: 'Portland Pozzolana Cement blended with fly ash for residential construction. Low heat of hydration and superior long-term strength.',
            subcategory: 'Cement',
            price: 360, originalPrice: 400,
            materialSpecifications: 'Type: PPC | Standard: IS 1489 Part 1 | Fly Ash: 15–35% | 28-day Strength: 33 MPa min',
            stock: 8000, tier: 'Standard Export', bulkInfo: 'Minimum order: 100 bags.', rating: 4.4, reviews: 210,
        },
        {
            productName: 'Ambuja White Cement (50 kg)',
            desc: 'Premium white cement for decorative plasterwork, tile grouting, and architectural finishes. High whiteness index.',
            subcategory: 'Cement',
            price: 850, originalPrice: 950,
            materialSpecifications: 'Type: White OPC | Whiteness: ≥87% | Strength: 33 MPa | IS 8042 | 50 kg bag',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Minimum order: 20 bags.', rating: 4.5, reviews: 132,
        },
        {
            productName: 'Rapid Hardening Cement 43 Grade (50 kg)',
            desc: 'Fast-setting cement for urgent repair work and precast elements. Achieves 3-day strength equivalent to 28-day OPC strength.',
            subcategory: 'Cement',
            price: 480, originalPrice: 540,
            materialSpecifications: 'Grade: 43 RHC | Standard: IS 8041 | 1-day Strength: 16 MPa | 3-day Strength: 27 MPa',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Minimum order: 50 bags.', rating: 4.3, reviews: 87,
        },
        {
            productName: 'Ready Mix Concrete M25 Grade (per m³)',
            desc: 'Plant-batched M25 concrete ready for direct pour. Used for slabs, beams, and columns in residential and commercial projects.',
            subcategory: 'Ready Mix Concrete',
            price: 5200, originalPrice: 5600,
            materialSpecifications: 'Mix: M25 | w/c Ratio: 0.45 | Slump: 100–120 mm | IS 456:2000 | Delivery: per m³',
            stock: 500, tier: 'LTL Freight Only', bulkInfo: 'Minimum order: 6 m³. Transit mixer within 30 km.', rating: 4.3, reviews: 85,
        },
        {
            productName: 'Ready Mix Concrete M30 Grade (per m³)',
            desc: 'High-strength M30 plant-batched concrete for commercial slabs, basement retaining walls, and heavy-load structures.',
            subcategory: 'Ready Mix Concrete',
            price: 5800, originalPrice: 6300,
            materialSpecifications: 'Mix: M30 | w/c Ratio: 0.42 | Slump: 100–125 mm | IS 456:2000 | Delivery: per m³',
            stock: 400, tier: 'LTL Freight Only', bulkInfo: 'Minimum order: 6 m³.', rating: 4.4, reviews: 62,
        },
        {
            productName: 'Siporex AAC Block 600×200×150 mm',
            desc: 'Autoclaved Aerated Concrete block — lightweight, thermally insulating, and dimensionally accurate for fast masonry construction.',
            subcategory: 'AAC Blocks',
            price: 44, originalPrice: 52,
            materialSpecifications: 'Size: 600×200×150 mm | Density: 550–650 kg/m³ | Compressive: 3.5 N/mm² | IS 2185 Part 3',
            stock: 20000, tier: 'Bulk Distribution', bulkInfo: 'Pallet: 80 blocks. Truck = ~2400 blocks.', rating: 4.5, reviews: 415,
        },
        {
            productName: 'Concrete Hollow Block 400×200×200 mm',
            desc: 'Load-bearing hollow concrete block for boundary walls, partition walls, and non-structural masonry applications.',
            subcategory: 'Concrete Blocks',
            price: 36, originalPrice: 42,
            materialSpecifications: 'Size: 400×200×200 mm | Compressive: 5 N/mm² | Water Absorption: <10% | IS 2185 Part 1',
            stock: 25000, tier: 'Bulk Distribution', bulkInfo: 'Truck load: ~1800 blocks.', rating: 4.2, reviews: 195,
        },
        {
            productName: 'Gypsum Plaster Machine Grade (25 kg)',
            desc: 'Machine-grade gypsum plaster for smooth internal wall and ceiling finishes. Eliminates the need for POP punning.',
            subcategory: 'Plasters',
            price: 310, originalPrice: 340,
            materialSpecifications: 'Setting Time: 25–40 min | Coverage: 8–9 m²/bag at 12 mm | IS 2547',
            stock: 5000, tier: 'Standard Export', bulkInfo: '40 bags per pallet.', rating: 4.4, reviews: 178,
        },
        {
            productName: 'Hindustan Cement Plaster of Paris (25 kg)',
            desc: 'Fine-grade Plaster of Paris for decorative mouldings, false ceiling work, and surface finishing.',
            subcategory: 'Plasters',
            price: 260, originalPrice: 295,
            materialSpecifications: 'Setting Time: 10–15 min | Coverage: 6–7 m²/bag at 12 mm | Whiteness: ≥80%',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Minimum order: 20 bags.', rating: 4.2, reviews: 143,
        },
        {
            productName: 'Pidilite MYK Laticrete Concrete Bonding Agent (5 L)',
            desc: 'Acrylic polymer bonding agent for improving adhesion of new concrete and plaster over old surfaces.',
            subcategory: 'Wall Reinforcement',
            price: 1100, originalPrice: 1250,
            materialSpecifications: 'Type: Acrylic | Dilution: 1:2 water | Coverage: 8–10 m²/L | Dry Time: 30 min',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 4 units.', rating: 4.4, reviews: 98,
        },
    ],

    'Tiles & Flooring': [
        {
            productName: 'Kajaria Double-Charged Vitrified Tile 600×600 mm — Glacial White',
            desc: 'Double-charged vitrified tile with high scratch resistance and low water absorption. Ideal for living rooms and lobbies.',
            subcategory: 'Vitrified Tiles',
            price: 58, originalPrice: 70,
            materialSpecifications: 'Size: 600×600 mm | Thickness: 9.5 mm | Water Absorption: <0.5% | Abrasion: PEI V | IS 15622',
            stock: 12000, tier: 'Standard Export', bulkInfo: 'Box: 4 tiles (1.44 m²). Price per tile.', rating: 4.5, reviews: 260,
        },
        {
            productName: 'Somany Polished Vitrified Tile 800×800 mm — Bianco Statuario',
            desc: 'Large-format full-body vitrified tile with marble-inspired pattern. High gloss finish for premium flooring.',
            subcategory: 'Vitrified Tiles',
            price: 95, originalPrice: 115,
            materialSpecifications: 'Size: 800×800 mm | Thickness: 10 mm | Water Absorption: <0.1% | PEI V | IS 15622',
            stock: 6000, tier: 'Standard Export', bulkInfo: 'Box: 3 tiles (1.92 m²). Price per tile.', rating: 4.6, reviews: 188,
        },
        {
            productName: 'Johnson Ceramic Floor Tile 300×300 mm — Anti-Skid Beige',
            desc: 'Anti-skid ceramic floor tile for bathrooms, kitchens, and outdoor areas. Textured surface for safe wet environments.',
            subcategory: 'Floor Tiles',
            price: 22, originalPrice: 28,
            materialSpecifications: 'Size: 300×300 mm | Finish: Anti-Skid | COF: >0.6 | Water Absorption: 6–10% | IS 13755',
            stock: 18000, tier: 'Standard Export', bulkInfo: 'Box: 16 tiles (1.44 m²). Price per tile.', rating: 4.3, reviews: 310,
        },
        {
            productName: 'Johnson Ceramic Wall Tile 300×450 mm — Ivory Matt',
            desc: 'Matt-finish ceramic wall tile for bathrooms, kitchens, and utility areas. Easy to cut and install.',
            subcategory: 'Wall Tiles',
            price: 32, originalPrice: 38,
            materialSpecifications: 'Size: 300×450 mm | Finish: Matt | Water Absorption: 6–10% | Breaking Strength: >250 N | IS 13753',
            stock: 15000, tier: 'Standard Export', bulkInfo: 'Box: 8 tiles (1.08 m²). Price per tile.', rating: 4.2, reviews: 195,
        },
        {
            productName: 'Orientbell Subway Wall Tile 75×300 mm — Glossy White',
            desc: 'Classic subway format ceramic wall tile in high-gloss white. Ideal for backsplashes, restaurants, and retro-style interiors.',
            subcategory: 'Wall Tiles',
            price: 28, originalPrice: 34,
            materialSpecifications: 'Size: 75×300 mm | Finish: High Gloss | Water Absorption: 10–20% | IS 13753',
            stock: 10000, tier: 'Standard Export', bulkInfo: 'Box: 44 tiles (0.99 m²). Price per tile.', rating: 4.3, reviews: 147,
        },
        {
            productName: 'Italian Carrara Marble Slab 18 mm — Polished',
            desc: 'Premium imported Carrara marble with natural veining patterns. Perfect for feature walls, countertops, and luxury flooring.',
            subcategory: 'Marble',
            price: 320, originalPrice: 380,
            materialSpecifications: 'Origin: Carrara, Italy | Thickness: 18 mm | Finish: Polished | Water Absorption: 0.2% | Per sq ft',
            stock: 2000, tier: 'Custom Fab', bulkInfo: 'Custom cutting available. Min. order: 100 sq ft.', rating: 4.7, reviews: 88,
        },
        {
            productName: 'Black Galaxy Granite Slab 18 mm — Polished',
            desc: 'Premium Indian Black Galaxy granite with golden speckles. Suitable for countertops and flooring.',
            subcategory: 'Granite',
            price: 180, originalPrice: 220,
            materialSpecifications: 'Origin: Andhra Pradesh, India | Thickness: 18 mm | Finish: Polished | Compressive: 180 MPa | Per sq ft',
            stock: 3000, tier: 'Custom Fab', bulkInfo: 'Custom cutting available. Min. order: 50 sq ft.', rating: 4.6, reviews: 112,
        },
        {
            productName: 'Absolute Black Granite Slab 20 mm — Flamed',
            desc: 'Jet-black granite with a flamed finish for outdoor paving, steps, and landscape flooring.',
            subcategory: 'Granite',
            price: 155, originalPrice: 190,
            materialSpecifications: 'Origin: Karnataka | Thickness: 20 mm | Finish: Flamed | Slip Resistance: R11 | Per sq ft',
            stock: 2500, tier: 'Custom Fab', bulkInfo: 'Min. order: 50 sq ft.', rating: 4.4, reviews: 73,
        },
        {
            productName: 'Laticrete 254 Platinum Tile Adhesive (20 kg)',
            desc: 'Polymer-modified cementitious tile adhesive for fixing ceramic, vitrified, and natural stone on walls and floors.',
            subcategory: 'Tile Adhesives',
            price: 620, originalPrice: 680,
            materialSpecifications: 'Coverage: 4–5 m²/bag at 6 mm | Open Time: 20 min | Shear Strength: >1 N/mm² | IS 15477',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Pallet: 40 bags.', rating: 4.4, reviews: 143,
        },
        {
            productName: 'Mapei Ultracolor Plus Tile Grout — 5 kg (Ivory)',
            desc: 'Ready-to-use cementitious grout with anti-mould protection for wall and floor tile joints from 2–20 mm.',
            subcategory: 'Tile Grouts',
            price: 480, originalPrice: 550,
            materialSpecifications: 'Joint Width: 2–20 mm | Coverage: ~1.5 m²/kg (3 mm joint, 300×300 tile) | Dry Time: 24 hrs',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.5, reviews: 168,
        },
        {
            productName: 'Roff Tileclean Tile & Grout Cleaner (1 L)',
            desc: 'Acid-based tile cleaner for removing cement haze, grout smears, and mineral deposits from new tile installations.',
            subcategory: 'Tile Cleaners',
            price: 220, originalPrice: 260,
            materialSpecifications: 'Type: Acid-based | Dilution: 1:4 | Safe for: Ceramic, Vitrified | Avoid: Marble, Limestone',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 12 units.', rating: 4.3, reviews: 94,
        },
    ],

    'Paints & Finishes': [
        {
            productName: 'Asian Paints Royale Luxury Emulsion — 20 L',
            desc: 'Premium interior emulsion paint with smooth finish, superior coverage, and low VOC for healthy indoor air quality.',
            subcategory: 'Interior Paints',
            price: 4200, originalPrice: 4700,
            materialSpecifications: 'Finish: Sheen | Coverage: 14–16 m²/L | VOC: <50 g/L | Dry Time: 2 hrs | Dilution: 20% water',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 pails.', rating: 4.6, reviews: 310,
        },
        {
            productName: 'Nerolac Impressions Interior Emulsion — 20 L',
            desc: 'Anti-bacterial interior emulsion with washability and smooth sheen finish for bedrooms and living areas.',
            subcategory: 'Interior Paints',
            price: 3800, originalPrice: 4300,
            materialSpecifications: 'Finish: Sheen | Coverage: 13–15 m²/L | Anti-Bacterial: Yes | VOC: <60 g/L | IS 15489',
            stock: 1800, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 pails.', rating: 4.4, reviews: 225,
        },
        {
            productName: 'Berger WeatherCoat Exterior Emulsion — 20 L',
            desc: 'High-build exterior emulsion with dirt-resistance and UV protection. Ideal for external walls in tropical climates.',
            subcategory: 'Exterior Paints',
            price: 5200, originalPrice: 5800,
            materialSpecifications: 'Finish: Flat | Coverage: 12–14 m²/L | UV Resistance: High | Water Resistance: ≥72 hrs | IS 15489',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Pallet: 20 pails.', rating: 4.5, reviews: 198,
        },
        {
            productName: 'Asian Paints Apex Exterior Emulsion — 20 L',
            desc: 'Silicone-modified exterior emulsion paint with 7-year protection against weathering, fungus, and algae.',
            subcategory: 'Exterior Paints',
            price: 4900, originalPrice: 5500,
            materialSpecifications: 'Finish: Flat | Coverage: 12–14 m²/L | Fungal Resistance: Yes | Alkali Resistance: Yes',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 pails.', rating: 4.5, reviews: 172,
        },
        {
            productName: 'Asian Paints Primer Interior — 20 L',
            desc: 'Water-based interior primer for new and repainting jobs. Provides excellent adhesion for topcoats on plaster and concrete.',
            subcategory: 'Primers',
            price: 2200, originalPrice: 2600,
            materialSpecifications: 'Base: Water | Coverage: 10–12 m²/L | Dry Time: 2 hrs | Recoat: 4 hrs | IS 109',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 pails.', rating: 4.3, reviews: 187,
        },
        {
            productName: 'Dulux Wall Putty White Cement Base (40 kg)',
            desc: 'White cement-based putty for smooth base coat on interior walls before painting. Fills hairline cracks.',
            subcategory: 'Putty',
            price: 950, originalPrice: 1050,
            materialSpecifications: 'Base: White Cement | Coverage: 10–12 m²/kg | Dry Time: 4 hrs | Thickness: 1–2 mm',
            stock: 6000, tier: 'Bulk Distribution', bulkInfo: 'Pallet: 25 bags.', rating: 4.3, reviews: 245,
        },
        {
            productName: 'Pidilite Dr. Fixit Dampshield Waterproof Primer — 20 L',
            desc: 'Polymer-modified waterproof primer that blocks rising dampness and prevents efflorescence on walls.',
            subcategory: 'Waterproof Primers',
            price: 2800, originalPrice: 3100,
            materialSpecifications: 'Coverage: 8–10 m²/L | Dry Time: 4 hrs | Application: Brush/Roller',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Minimum order: 3 units.', rating: 4.5, reviews: 167,
        },
        {
            productName: 'Nippon Texture Finish Stone Effect (4 kg)',
            desc: 'Decorative stone-effect texture coating for feature walls and facades. Premium natural stone appearance.',
            subcategory: 'Texture Finishes',
            price: 1650, originalPrice: 1900,
            materialSpecifications: 'Coverage: 1.5–2 m²/kg | Finish: Stone Effect | Dry Time: 4 hrs | Ready to use',
            stock: 800, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 units.', rating: 4.3, reviews: 92,
        },
        {
            productName: 'Berger Bison Wood Stain — 1 L (Walnut)',
            desc: 'Penetrating wood stain for interior and exterior timber. Enhances grain and provides UV protection.',
            subcategory: 'Wood Coatings',
            price: 680, originalPrice: 780,
            materialSpecifications: 'Type: Oil-based | Coverage: 12–14 m²/L | Dry Time: 2 hrs | Coats: 2 recommended | IS 345',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 12 units.', rating: 4.4, reviews: 113,
        },
        {
            productName: 'Asian Paints Apcolite Premium Enamel — 4 L (White)',
            desc: 'Synthetic enamel paint for wood and metal surfaces. High gloss, hard-wearing finish with excellent durability.',
            subcategory: 'Enamels',
            price: 1450, originalPrice: 1680,
            materialSpecifications: 'Finish: High Gloss | Coverage: 13–15 m²/L | Dry Time: 6 hrs | Thinner: Mineral Turpentine',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 4 units.', rating: 4.4, reviews: 204,
        },
        {
            productName: '3M Scotch Blue Masking Tape 48 mm×50 m (Pack of 6)',
            desc: 'Professional painter\'s masking tape for sharp paint lines on walls, trim, glass, and metal. Clean removal up to 14 days.',
            subcategory: 'Masking Tape',
            price: 780, originalPrice: 920,
            materialSpecifications: 'Width: 48 mm | Length: 50 m | Adhesion: Medium | Temp: Up to 80°C | Pack: 6 rolls',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.6, reviews: 268,
        },
    ],

    'Construction Chemicals': [
        {
            productName: 'Pidilite Fevicol SR-998 Wood Adhesive (5 kg)',
            desc: 'Synthetic resin adhesive for bonding plywood, MDF, laminates, and veneer in furniture and woodwork.',
            subcategory: 'Wood Adhesives',
            price: 780, originalPrice: 880,
            materialSpecifications: 'Type: PVA Resin | Dry Time: 20–30 min | Bond Strength: >1.5 N/mm² | Coverage: 200–250 g/m²',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.7, reviews: 385,
        },
        {
            productName: 'Pidilite Fevicol Marine Waterproof Adhesive (1 kg)',
            desc: 'Marine-grade waterproof PVA adhesive for exterior wood joints, boat building, and wet-area applications.',
            subcategory: 'Wood Adhesives',
            price: 320, originalPrice: 375,
            materialSpecifications: 'Type: Waterproof PVA | Water Resistance: Type II | Dry Time: 30 min | Press Time: 1 hr',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 12 units.', rating: 4.5, reviews: 152,
        },
        {
            productName: 'Laticrete 254 Platinum Tile Adhesive (20 kg)',
            desc: 'Polymer-modified thin-set mortar for bonding heavy natural stone, porcelain, and large-format tiles.',
            subcategory: 'Tile Adhesives',
            price: 650, originalPrice: 720,
            materialSpecifications: 'Coverage: 3–4 m²/bag at 6 mm | Open Time: 30 min | Tensile: >1.4 N/mm² | IS 15477',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Pallet: 40 bags.', rating: 4.5, reviews: 178,
        },
        {
            productName: 'Sika Epoxy 2-Component Adhesive (500 mL)',
            desc: 'High-strength two-component epoxy for structural bonding of concrete, metal, and masonry substrates.',
            subcategory: 'Epoxy Adhesives',
            price: 1450, originalPrice: 1650,
            materialSpecifications: 'Mix Ratio: 1:1 | Open Time: 45 min | Compressive: 70 N/mm² | Tensile: 30 N/mm²',
            stock: 800, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.6, reviews: 75,
        },
        {
            productName: 'Sikaflex-291 Polyurethane Sealant (300 mL)',
            desc: 'One-component polyurethane sealant for waterproof joints in construction and industrial applications.',
            subcategory: 'Sealants',
            price: 520, originalPrice: 590,
            materialSpecifications: 'Type: PU | Shore A: 45 | Elongation: 600% | Movement: ±25% | Application: Cartridge gun',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 12 cartridges.', rating: 4.5, reviews: 132,
        },
        {
            productName: 'GE Sealants Silicone Sanitary Sealant — 280 mL (White)',
            desc: 'Mould-resistant silicone sealant for wet areas including shower enclosures, baths, and kitchen joints.',
            subcategory: 'Sealants',
            price: 380, originalPrice: 440,
            materialSpecifications: 'Type: Acetoxy Silicone | Cure Time: 24 hrs | Temp Range: -40 to 150°C | Anti-Mould: Yes',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 12 cartridges.', rating: 4.4, reviews: 215,
        },
        {
            productName: 'Mapei Keracolor S Tile Grout — 5 kg (Grey)',
            desc: 'Polymer-enriched sand grout for joints 2–12 mm. Crack-resistant and water-repellent for floor and wall tiles.',
            subcategory: 'Grouts',
            price: 420, originalPrice: 490,
            materialSpecifications: 'Joint Width: 2–12 mm | Coverage: 1–2 m²/kg | Dry Time: 24 hrs | Shrinkage: <0.1%',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.4, reviews: 138,
        },
        {
            productName: 'Pidilite Dr. Fixit SBR Latex (5 L)',
            desc: 'Styrene-Butadiene Rubber latex for modifying cement mortar to improve bonding, flexibility, and waterproofing.',
            subcategory: 'SBR Latex',
            price: 1200, originalPrice: 1350,
            materialSpecifications: 'Type: SBR | Mix Ratio: 1:2 with cement | Coverage: 0.5–0.7 L/m² | IS 9103',
            stock: 1800, tier: 'Standard Export', bulkInfo: 'Case: 4 units.', rating: 4.4, reviews: 119,
        },
        {
            productName: 'Fosroc Nitobond Acrylic Crack Filler (1 kg)',
            desc: 'Ready-to-use acrylic crack filler for sealing hairline cracks and holes in concrete and masonry walls.',
            subcategory: 'Crack Fillers',
            price: 320, originalPrice: 370,
            materialSpecifications: 'Base: Acrylic | Application: Putty knife | Paintable: Yes | Coverage: ~0.5 kg/m run',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 12 units.', rating: 4.3, reviews: 157,
        },
        {
            productName: 'Pidilite Dr. Fixit Raincoat Waterproof Coating — 10 L',
            desc: 'Elastomeric acrylic waterproof coating for terraces, sunshades, and parapets. Bridges hairline cracks.',
            subcategory: 'Waterproof Coatings',
            price: 3200, originalPrice: 3700,
            materialSpecifications: 'Coverage: 3–4 m²/L (2 coats) | Elongation: 200% | Dry Time: 2 hrs | UV Stable: Yes',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Minimum order: 3 units.', rating: 4.5, reviews: 183,
        },
        {
            productName: 'Fosroc Polyurethane Waterproof Coating — 10 L',
            desc: 'Two-component polyurethane waterproof membrane for rooftop decks, podiums, and wet rooms. Seamless finish.',
            subcategory: 'Waterproof Coatings',
            price: 5800, originalPrice: 6500,
            materialSpecifications: 'Components: 2 | Elongation: 350% | Tensile: 8 N/mm² | Film Thickness: 2 mm min | Coverage: 1.5 kg/m²',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Kit includes part A and part B. Min. order: 2 kits.', rating: 4.6, reviews: 74,
        },
    ],

    'Plywood, Laminates & Boards': [
        {
            productName: 'Century Club Prime BWR Plywood 2440×1220×18 mm',
            desc: 'Boiling Water Resistant plywood for kitchen, bathroom, and exterior use. Phenol-formaldehyde resin bond.',
            subcategory: 'Plywood',
            price: 3200, originalPrice: 3600,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 18 mm | Grade: BWR | Glue: PF Resin | IS 303',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.5, reviews: 210,
        },
        {
            productName: 'Greenply Gold MR Plywood 2440×1220×12 mm',
            desc: 'Moisture-resistant commercial plywood for interior furniture and cabinetry. Uniform thickness and smooth surface.',
            subcategory: 'Plywood',
            price: 1850, originalPrice: 2100,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 12 mm | Grade: MR | Glue: UF Resin | IS 303',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.3, reviews: 185,
        },
        {
            productName: 'Greenply Interior MDF Board 2440×1220×12 mm',
            desc: 'Medium Density Fibreboard for interior furniture, cabinetry, and decorative panelling. Easy to machine.',
            subcategory: 'MDF Boards',
            price: 1650, originalPrice: 1900,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 12 mm | Density: 750 kg/m³ | Formaldehyde: E1 | IS 12406',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Bundle: 20 sheets.', rating: 4.3, reviews: 148,
        },
        {
            productName: 'Greenply Moisture Resistant MDF 2440×1220×18 mm',
            desc: 'Moisture-resistant MDF for kitchen and bathroom cabinetry. Swelling <6% after 24-hour water soak.',
            subcategory: 'MDF Boards',
            price: 2400, originalPrice: 2750,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 18 mm | Density: 780 kg/m³ | Water Resistance: IS 12406 MR | E1',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.5, reviews: 116,
        },
        {
            productName: 'Action HDHMR Board 2440×1220×18 mm',
            desc: 'High Density High Moisture Resistant board — superior screw holding and water resistance for modular kitchens.',
            subcategory: 'HDHMR Boards',
            price: 2800, originalPrice: 3200,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 18 mm | Density: 850 kg/m³ | IS 12406 Type IV',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.6, reviews: 173,
        },
        {
            productName: 'National Flush Block Board 2440×1220×19 mm',
            desc: 'Block board with solid timber core for shelving, worktops, and table tops. High rigidity with low warping.',
            subcategory: 'Block Boards',
            price: 2600, originalPrice: 3000,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 19 mm | Core: Hardwood Strips | Face: MR Ply | IS 1659',
            stock: 1000, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.4, reviews: 132,
        },
        {
            productName: 'Duratex Particle Board 2440×1220×18 mm',
            desc: 'Melamine-faced particle board for flat-pack furniture, shelving, and storage units. Smooth surface finish.',
            subcategory: 'Particle Boards',
            price: 1200, originalPrice: 1400,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 18 mm | Density: 650 kg/m³ | Face: Melamine | IS 12823',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Bundle: 20 sheets.', rating: 4.1, reviews: 94,
        },
        {
            productName: 'Kitply Marine BWP Plywood 2440×1220×19 mm',
            desc: 'Marine-grade BWP plywood with maximum moisture resistance for outdoor furniture and high-humidity environments.',
            subcategory: 'Boiling Water Resistant Boards',
            price: 4100, originalPrice: 4600,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 19 mm | Grade: BWP/Marine | IS 710',
            stock: 900, tier: 'Standard Export', bulkInfo: 'Bundle: 10 sheets.', rating: 4.7, reviews: 128,
        },
        {
            productName: 'Merino High-Gloss Laminate 2440×1220×1 mm — Arctic White',
            desc: 'High-pressure laminate for furniture and cabinetry surfaces. Scratch-resistant with vibrant colour.',
            subcategory: 'Laminates',
            price: 1200, originalPrice: 1400,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 1 mm | Finish: High Gloss | Abrasion: 150 cycles | IS 2046',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Bundle: 20 sheets.', rating: 4.4, reviews: 195,
        },
        {
            productName: 'Greenlam Suede Matt Laminate 2440×1220×1 mm — Graphite',
            desc: 'Matt suede-texture laminate for contemporary furniture and modular kitchen shutters. Fingerprint-resistant surface.',
            subcategory: 'Laminates',
            price: 1450, originalPrice: 1700,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 1 mm | Finish: Suede Matt | Surface: Anti-fingerprint | IS 2046',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Bundle: 20 sheets.', rating: 4.5, reviews: 147,
        },
        {
            productName: 'Greenply Teak Wood Veneer Sheet 2440×1220×0.5 mm',
            desc: 'Natural teak veneer for furniture, door faces, and decorative panels. Uniform grain with warm golden-brown tone.',
            subcategory: 'Veneers',
            price: 980, originalPrice: 1150,
            materialSpecifications: 'Size: 2440×1220 mm | Thickness: 0.5 mm | Wood: Natural Teak | Backing: Paper | IS 848',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Bundle: 25 sheets.', rating: 4.5, reviews: 108,
        },
    ],

    'Doors & Windows': [
        {
            productName: 'Greenply Flush Door 2100×900×35 mm — MR Commercial',
            desc: 'Moisture-resistant flush door with solid block board core for internal doors in offices and residential buildings.',
            subcategory: 'Flush Doors',
            price: 4200, originalPrice: 4800,
            materialSpecifications: 'Size: 2100×900×35 mm | Core: Block Board | Face: 3 mm MR Ply | IS 2202 Part 1',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 doors.', rating: 4.4, reviews: 142,
        },
        {
            productName: 'Durodoors Steel Security Door 2100×900 mm — Anti-Rust',
            desc: 'Heavy-gauge steel security door with multi-point locking. Powder-coated with anti-rust primer for exterior use.',
            subcategory: 'Flush Doors',
            price: 8500, originalPrice: 9800,
            materialSpecifications: 'Size: 2100×900 mm | Steel: 18 Gauge | Locking: 3-point | Finish: Powder Coat | Hinges: 3 heavy-duty',
            stock: 300, tier: 'Standard Export', bulkInfo: 'Minimum order: 2 doors.', rating: 4.5, reviews: 98,
        },
        {
            productName: 'Burma Teak Panel Door 2100×900×45 mm — 6-Panel',
            desc: 'Solid Burma teak panel door with raised mouldings for main entrances and master bedrooms.',
            subcategory: 'Panel Doors',
            price: 18500, originalPrice: 21000,
            materialSpecifications: 'Size: 2100×900×45 mm | Wood: Burma Teak | Panels: 6 raised | Finish: Raw for polish',
            stock: 150, tier: 'Custom Fab', bulkInfo: 'Custom sizes available. Lead time: 10–14 days.', rating: 4.7, reviews: 53,
        },
        {
            productName: 'WPC Door Frame 2400×100×50 mm — Teak Finish',
            desc: 'Wood Polymer Composite door frame — termite-proof, water-resistant, and dimensionally stable. Ready to fix.',
            subcategory: 'Panel Doors',
            price: 1800, originalPrice: 2100,
            materialSpecifications: 'Size: 2400×100×50 mm | Material: WPC | Finish: Teak Grain | Termite Proof: Yes | Screw: Holds well',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Sold per frame (set of 3 pieces).', rating: 4.4, reviews: 177,
        },
        {
            productName: 'UPVC Casement Window 1200×1200 mm — 5-Chamber',
            desc: 'Multi-chamber UPVC casement window with galvanised steel reinforcement. Energy-efficient with excellent weather sealing.',
            subcategory: 'UPVC Windows',
            price: 12500, originalPrice: 14000,
            materialSpecifications: 'Size: 1200×1200 mm | Profile: 5-chamber | Steel: Galvanised | Glass: 5 mm | U-Value: 2.8',
            stock: 300, tier: 'Custom Fab', bulkInfo: 'Custom sizes. Lead time: 7–10 days.', rating: 4.5, reviews: 97,
        },
        {
            productName: 'UPVC Sliding Window 1800×1200 mm — 3-Track',
            desc: 'Three-track UPVC sliding window for wide openings. Thermal break profile with weather-strip gaskets.',
            subcategory: 'UPVC Windows',
            price: 16500, originalPrice: 18800,
            materialSpecifications: 'Size: 1800×1200 mm | Profile: 3-track | Steel: Galvanised | Glass: 5 mm | Tracks: 3',
            stock: 200, tier: 'Custom Fab', bulkInfo: 'Custom sizes. Lead time: 7–10 days.', rating: 4.4, reviews: 68,
        },
        {
            productName: 'Aluminium Sliding Window 1500×1200 mm — Powder Coated',
            desc: 'Aluminium sliding window with heavy-gauge sections and powder-coated finish for commercial applications.',
            subcategory: 'Aluminium Windows',
            price: 9800, originalPrice: 11200,
            materialSpecifications: 'Size: 1500×1200 mm | Section: 1.4 mm | Finish: Powder Coat | Glass: 5 mm | 2-track',
            stock: 400, tier: 'Custom Fab', bulkInfo: 'Custom sizes and finishes.', rating: 4.3, reviews: 78,
        },
        {
            productName: 'Aluminium Fixed Window with Mesh 900×1200 mm',
            desc: 'Fixed aluminium window with integrated SS mosquito mesh for ventilation without insect ingress.',
            subcategory: 'Aluminium Windows',
            price: 5200, originalPrice: 6000,
            materialSpecifications: 'Size: 900×1200 mm | Mesh: SS 18×16 | Section: 1.2 mm | Glass: 5 mm | Finish: Anodised',
            stock: 500, tier: 'Custom Fab', bulkInfo: 'Custom sizes available.', rating: 4.3, reviews: 54,
        },
        {
            productName: 'Toughened Glass Panel 8 mm — Clear (1200×2400 mm)',
            desc: 'Tempered safety glass for partitions, shower enclosures, and glazed doors. 5× stronger than float glass.',
            subcategory: 'Glass Panels',
            price: 8500, originalPrice: 9800,
            materialSpecifications: 'Size: 1200×2400 mm | Thickness: 8 mm | Type: Toughened | IS 2553 Part 1',
            stock: 250, tier: 'Custom Fab', bulkInfo: 'Custom sizes. Min. order: 5 panels.', rating: 4.5, reviews: 64,
        },
        {
            productName: 'Frosted Toughened Glass Panel 6 mm (900×2100 mm)',
            desc: 'Acid-etched frosted tempered glass for bathroom partitions, office dividers, and privacy screens.',
            subcategory: 'Glass Panels',
            price: 5800, originalPrice: 6700,
            materialSpecifications: 'Size: 900×2100 mm | Thickness: 6 mm | Finish: Frosted | Type: Toughened | IS 2553',
            stock: 200, tier: 'Custom Fab', bulkInfo: 'Custom sizes. Min. order: 3 panels.', rating: 4.4, reviews: 42,
        },
    ],

    'Hardware & Fittings': [
        {
            productName: 'Hettich Sensys Soft-Close Concealed Hinge (Pack of 20)',
            desc: 'Soft-close concealed cabinet hinge with integrated damper. 110° opening angle for 18–22 mm boards.',
            subcategory: 'Hinges',
            price: 1800, originalPrice: 2100,
            materialSpecifications: 'Opening: 110° | Overlay: Full/Half/Inset | Board: 18–22 mm | Material: Steel Zinc | Pack: 20',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.7, reviews: 340,
        },
        {
            productName: 'Ebco Hydraulic Floor Spring — Heavy Duty (100 kg)',
            desc: 'Floor-spring door closer for frameless glass or solid doors up to 100 kg. Adjustable closing speed.',
            subcategory: 'Door Hardware',
            price: 2800, originalPrice: 3300,
            materialSpecifications: 'Door Weight: Up to 100 kg | Opening: 90° | Adjustment: Speed + Backcheck | Body: Cast Iron',
            stock: 500, tier: 'Standard Export', bulkInfo: 'Includes top pivot and cover plate.', rating: 4.5, reviews: 112,
        },
        {
            productName: 'Dorma TS-83 Surface-Mounted Door Closer',
            desc: 'Hydraulic rack-and-pinion door closer with back-check and variable closing force for EN 1–6 door sizes.',
            subcategory: 'Door Hardware',
            price: 3200, originalPrice: 3700,
            materialSpecifications: 'EN Size: 1–6 | Back-Check: Yes | Body: Die-cast Zinc | Max Door Width: 1200 mm | Weight: 1.6 kg',
            stock: 400, tier: 'Standard Export', bulkInfo: 'Includes all mounting hardware.', rating: 4.6, reviews: 87,
        },
        {
            productName: 'Godrej 4-Lever Mortise Lock — Stainless Steel',
            desc: 'Heavy-duty 4-lever mortise lock with deadbolt for main entrance doors. Anti-pick and anti-drill.',
            subcategory: 'Locks',
            price: 1450, originalPrice: 1700,
            materialSpecifications: 'Levers: 4 | Body: SS | Backset: 60 mm | Deadbolt: Full | IS 2209',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Minimum order: 10 units.', rating: 4.5, reviews: 215,
        },
        {
            productName: 'Yale Digital Lock Y-217 — RFID + PIN',
            desc: 'Digital mortise lock with RFID card, PIN code, and mechanical key backup. Auto-lock function.',
            subcategory: 'Locks',
            price: 8500, originalPrice: 9800,
            materialSpecifications: 'Access: RFID + 4–8 digit PIN + Key | Auto-Lock: Yes | Battery: 4×AA | Body: Zinc Die-cast',
            stock: 200, tier: 'Standard Export', bulkInfo: 'Includes 5 RFID cards and 3 mechanical keys.', rating: 4.5, reviews: 73,
        },
        {
            productName: 'Hettich Quadro Drawer Side 500 mm — Undermount (Pair)',
            desc: 'Steel drawer side with integrated undermount runner for modular kitchen and wardrobe drawers.',
            subcategory: 'Drawer Slides',
            price: 1650, originalPrice: 1900,
            materialSpecifications: 'Length: 500 mm | Load: 30 kg | Finish: Anthracite | Type: Undermount | Extension: Full',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 10 pairs.', rating: 4.6, reviews: 178,
        },
        {
            productName: 'Hettich Telescopic Channel 450 mm — Full Extension (Pair)',
            desc: 'Side-mounted telescopic drawer runner with full extension and soft-close. 40 kg load capacity.',
            subcategory: 'Telescopic Channels',
            price: 480, originalPrice: 560,
            materialSpecifications: 'Length: 450 mm | Load: 40 kg | Extension: Full | Soft-Close: Yes | Finish: Nickel | Pair',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 20 pairs.', rating: 4.5, reviews: 264,
        },
        {
            productName: 'Stanley SS Door Handle — Lever G Series (Pair)',
            desc: 'Lever-style door handle in brushed stainless steel. Compatible with standard mortise locks.',
            subcategory: 'Handles',
            price: 680, originalPrice: 800,
            materialSpecifications: 'Material: SS 304 | Finish: Brushed | Spindle: 8×8 mm | Backplate: 55×155 mm | Pair',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 20 pairs.', rating: 4.4, reviews: 293,
        },
        {
            productName: 'Hafele Bow Handle 128 mm — Satin Nickel',
            desc: 'Cabinet bow handle for kitchen shutters and wardrobe drawers. Corrosion-resistant satin nickel finish.',
            subcategory: 'Handles',
            price: 180, originalPrice: 215,
            materialSpecifications: 'Hole Centre: 128 mm | Material: Zinc Alloy | Finish: Satin Nickel | Screw: M4×30 mm',
            stock: 5000, tier: 'Standard Export', bulkInfo: 'Case: 50 units.', rating: 4.4, reviews: 348,
        },
        {
            productName: 'Hilti Hex Bolt M10×75 mm Grade 8.8 (Box of 100)',
            desc: 'High-tensile hex bolts for structural steel connections and heavy-duty fastening applications.',
            subcategory: 'Fasteners',
            price: 580, originalPrice: 650,
            materialSpecifications: 'Size: M10×75 mm | Grade: 8.8 | Material: Carbon Steel | Finish: Zinc Plated | IS 1364 | 100 pcs',
            stock: 5000, tier: 'Bulk Distribution', bulkInfo: 'Box: 100 pcs. Case: 10 boxes.', rating: 4.3, reviews: 122,
        },
        {
            productName: 'Stainless Steel Tower Bolt — 300 mm (Pack of 10)',
            desc: 'Heavy-duty SS tower bolt for doors, gates, and windows. Smooth sliding action with strong body.',
            subcategory: 'General Hardware',
            price: 650, originalPrice: 760,
            materialSpecifications: 'Length: 300 mm | Material: SS 304 | Finish: Satin | Body: 12 mm Dia | Pack: 10 pcs',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.3, reviews: 147,
        },
    ],

    'Kitchen & Wardrobe Solutions': [
        {
            productName: 'Hettich Arcitech Pull-Out Pantry Unit — 600 mm',
            desc: 'Full-extension pull-out pantry unit with soft-close for modular kitchen column cabinets.',
            subcategory: 'Pantry Units',
            price: 14500, originalPrice: 16500,
            materialSpecifications: 'Cabinet Width: 600 mm | Depth: 550 mm | Load: 25 kg/shelf | Extension: Full | Soft-Close: Yes',
            stock: 200, tier: 'Standard Export', bulkInfo: 'Minimum order: 2 units.', rating: 4.7, reviews: 85,
        },
        {
            productName: 'Hafele Matrix Box P Drawer System — 500 mm (Pair)',
            desc: 'Steel drawer box with inner drawer option for deep base cabinets. Push-to-open compatible.',
            subcategory: 'Drawer Systems',
            price: 3800, originalPrice: 4500,
            materialSpecifications: 'Length: 500 mm | Height: 92 mm | Load: 35 kg | Finish: White Epoxy | Extension: Full | Soft-Close: Yes',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Case: 5 pairs.', rating: 4.6, reviews: 128,
        },
        {
            productName: 'Hettich Slido Wardrobe Sliding System — 2-Door 2.5 m',
            desc: 'Top-hung sliding door system for wardrobes. Soft-close deceleration with anti-jump track.',
            subcategory: 'Sliding Systems',
            price: 7200, originalPrice: 8500,
            materialSpecifications: 'Track: 2.5 m | Door Weight: 60 kg max/door | Soft-Close: Yes | Panel: 16–22 mm',
            stock: 400, tier: 'Standard Export', bulkInfo: 'Kit includes top track, runners, bottom guide.', rating: 4.6, reviews: 112,
        },
        {
            productName: 'Ebco Profile Door System — Aluminium Frame Kit (2.4 m)',
            desc: 'Aluminium profile frame system for modular wardrobe and cabinet shutters with integrated soft-close hinge.',
            subcategory: 'Door Systems',
            price: 4200, originalPrice: 4900,
            materialSpecifications: 'Profile Length: 2.4 m | Material: Aluminium | Compatible Panel: 4–6 mm | Finish: Champagne',
            stock: 500, tier: 'Standard Export', bulkInfo: 'Kit: top, bottom, 2 vertical profiles.', rating: 4.4, reviews: 76,
        },
        {
            productName: 'Hafele Dual Bin Pull-Out System — 2×14 L',
            desc: 'Dual-bin pull-out waste management unit for kitchen under-sink or base cabinet. Integrated soft-close.',
            subcategory: 'Waste Management',
            price: 3800, originalPrice: 4400,
            materialSpecifications: 'Bins: 2×14 L | Cabinet Width: 400 mm min | Depth: 500 mm | Material: PP + Steel Frame',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Minimum order: 2 units.', rating: 4.4, reviews: 97,
        },
        {
            productName: 'Hettich Gas Lift 140–240 N Flap System (Pair)',
            desc: 'Adjustable gas pressure lift for overhead kitchen flap doors. Smooth opening, holds at any angle.',
            subcategory: 'Gas Lifts',
            price: 2200, originalPrice: 2600,
            materialSpecifications: 'Force: 140–240 N adjustable | Door Weight: 4–10 kg | Door Width: 500–900 mm | Pair',
            stock: 900, tier: 'Standard Export', bulkInfo: 'Case: 10 pairs.', rating: 4.5, reviews: 73,
        },
        {
            productName: 'Ebco Oval Wardrobe Hanging Rail — 1.2 m (SS)',
            desc: 'Oval SS wardrobe hanging rail with flanged end supports for full-length garment storage.',
            subcategory: 'Wardrobe Rails',
            price: 480, originalPrice: 560,
            materialSpecifications: 'Length: 1.2 m | Section: 30×15 mm Oval | Material: SS 304 | Load: 15 kg | Includes supports',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.3, reviews: 135,
        },
        {
            productName: 'Häfele Wardrobe Trouser Pull-Out — 600 mm',
            desc: 'Extending trouser/tie rack for wardrobe base cabinets. Chrome-plated steel with full-extension slide.',
            subcategory: 'Wardrobe Accessories',
            price: 2800, originalPrice: 3300,
            materialSpecifications: 'Cabinet Width: 600 mm | Load: 10 kg | Extension: Full | Material: Chrome Steel | Rods: 10',
            stock: 400, tier: 'Standard Export', bulkInfo: 'Case: 5 units.', rating: 4.5, reviews: 63,
        },
        {
            productName: 'Hettich InnoTech Atira Pull-Out Base Unit — 450 mm',
            desc: 'Base cabinet pull-out with two-tier storage. Ideal for pots, pans, and heavy kitchen items.',
            subcategory: 'Pullout Systems',
            price: 6500, originalPrice: 7500,
            materialSpecifications: 'Cabinet Width: 450 mm | Load: 50 kg | Extension: Full | Soft-Close: Yes | Finish: Silver',
            stock: 300, tier: 'Standard Export', bulkInfo: 'Minimum order: 2 units.', rating: 4.6, reviews: 54,
        },
        {
            productName: 'Häfele Tall Cabinet Divider Storage Set — 600 mm',
            desc: 'Modular tall cabinet organiser for baking trays, chopping boards, and cutting boards with divider inserts.',
            subcategory: 'Storage Systems',
            price: 3200, originalPrice: 3800,
            materialSpecifications: 'Cabinet Width: 600 mm | Material: Chrome Wire | Dividers: 6 | Height: 400 mm | Adjustable: Yes',
            stock: 350, tier: 'Standard Export', bulkInfo: 'Minimum order: 2 units.', rating: 4.4, reviews: 47,
        },
    ],

    'Tools & Equipment': [
        {
            productName: 'Bosch GBH 2-26 DRE SDS-Plus Rotary Hammer',
            desc: 'Professional rotary hammer with 3-function mode: drilling, hammer drilling, and chiselling.',
            subcategory: 'Power Tools',
            price: 8900, originalPrice: 10500,
            materialSpecifications: 'Power: 800 W | Impact Energy: 2.7 J | Chuck: SDS-Plus | Max Concrete: 26 mm | Weight: 2.8 kg',
            stock: 300, tier: 'Standard Export', bulkInfo: 'Includes 3 drill bits and carry case.', rating: 4.8, reviews: 420,
        },
        {
            productName: 'Bosch GWS 750-100 Angle Grinder — 4 inch',
            desc: 'Compact angle grinder for cutting, grinding, and polishing metal, concrete, and stone. Restart protection.',
            subcategory: 'Power Tools',
            price: 3200, originalPrice: 3800,
            materialSpecifications: 'Power: 750 W | Disc: 100 mm | No-Load Speed: 11000 rpm | Spindle: M10 | Weight: 1.9 kg',
            stock: 400, tier: 'Standard Export', bulkInfo: 'Includes 1 grinding disc and carry case.', rating: 4.6, reviews: 315,
        },
        {
            productName: 'Makita BO5041 Random Orbital Sander — 125 mm',
            desc: 'Variable-speed random orbit sander with dust collection. Ideal for wood, MDF, and fibre finishing.',
            subcategory: 'Power Tools',
            price: 5200, originalPrice: 6100,
            materialSpecifications: 'Power: 300 W | Orbit: 2.8 mm | Pad: 125 mm | Speed: 4000–12000 rpm | Weight: 1.3 kg',
            stock: 250, tier: 'Standard Export', bulkInfo: 'Includes dust bag and carry case.', rating: 4.5, reviews: 185,
        },
        {
            productName: 'Stanley FatMax Tape Measure 8 m × 32 mm',
            desc: 'Heavy-duty professional tape with Tru-Zero hook, nylon-coated blade, and rubber grip.',
            subcategory: 'Measurement Tools',
            price: 780, originalPrice: 900,
            materialSpecifications: 'Length: 8 m | Blade Width: 32 mm | Standout: 3 m | Accuracy: Class II | Dual lock',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.6, reviews: 315,
        },
        {
            productName: 'Bosch GLM 50 C Laser Distance Meter',
            desc: 'Bluetooth-enabled laser distance meter with colour display. Measures up to 50 m with ±1.5 mm accuracy.',
            subcategory: 'Measurement Tools',
            price: 6800, originalPrice: 7900,
            materialSpecifications: 'Range: 50 m | Accuracy: ±1.5 mm | Bluetooth: Yes | Display: Colour | Battery: 2×AAA',
            stock: 200, tier: 'Standard Export', bulkInfo: 'Includes carry pouch and batteries.', rating: 4.7, reviews: 192,
        },
        {
            productName: 'Stanley Professional Box Spirit Level — 600 mm',
            desc: 'Aluminium box spirit level with 3 reinforced vials for horizontal, vertical, and 45° checks.',
            subcategory: 'Measurement Tools',
            price: 850, originalPrice: 1000,
            materialSpecifications: 'Length: 600 mm | Vials: 3 | Material: Aluminium | Accuracy: 0.5 mm/m | Shock Resistant: Yes',
            stock: 1000, tier: 'Standard Export', bulkInfo: 'Case: 6 units.', rating: 4.5, reviews: 227,
        },
        {
            productName: '3M 9502+ N95 Particulate Respirator (Pack of 20)',
            desc: 'Disposable N95 cup-shaped respirator for protection against fine dust, fumes, and aerosols.',
            subcategory: 'Protective Equipment',
            price: 1600, originalPrice: 1900,
            materialSpecifications: 'Standard: NIOSH N95 / IS 9473 | Filtration: ≥95% | Type: Disposable | Pack: 20 pcs',
            stock: 5000, tier: 'Bulk Distribution', bulkInfo: 'Case: 12 packs.', rating: 4.6, reviews: 278,
        },
        {
            productName: 'JSP EVO3 Hard Hat Safety Helmet — White',
            desc: 'Vented safety helmet with ratchet suspension for construction and industrial sites. Meets EN 397 and IS 2925.',
            subcategory: 'Protective Equipment',
            price: 680, originalPrice: 800,
            materialSpecifications: 'Material: HDPE Shell | Suspension: 6-point Ratchet | Weight: 350 g | IS 2925 | EN 397',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.5, reviews: 193,
        },
        {
            productName: 'Taparia Combination Spanner Set — 8 pcs (8–22 mm)',
            desc: 'Chrome vanadium combination spanner set with mirror-polished finish for structural and plumbing work.',
            subcategory: 'Hand Tools',
            price: 1350, originalPrice: 1600,
            materialSpecifications: 'Material: Cr-V Steel | Sizes: 8,10,12,13,14,17,19,22 mm | Finish: Mirror Polish | IS 2028',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 10 sets.', rating: 4.5, reviews: 230,
        },
        {
            productName: 'Taparia Heavy-Duty Hacksaw Frame — Adjustable 300–400 mm',
            desc: 'Adjustable tubular hacksaw frame with tension screw for smooth cutting of metal pipes and sections.',
            subcategory: 'Hand Tools',
            price: 320, originalPrice: 380,
            materialSpecifications: 'Frame: Steel Tubular | Blade Length: 300–400 mm (adjustable) | Tension: Thumb screw | IS 1574',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 12 units.', rating: 4.4, reviews: 178,
        },
        {
            productName: 'WD-40 Multi-Use Maintenance Spray — 450 mL',
            desc: 'Multi-purpose lubricant and rust preventative for tools, hinges, nuts, and bolts. Displaces moisture.',
            subcategory: 'Maintenance Products',
            price: 380, originalPrice: 440,
            materialSpecifications: 'Volume: 450 mL | Type: Aerosol | Use: Lubrication, Rust Prevention, Moisture Displacement',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Case: 12 cans.', rating: 4.7, reviews: 412,
        },
    ],

    'Electrical': [
        {
            productName: 'Finolex 4 sq.mm FR Copper Wire — 90 m Coil (Red)',
            desc: 'PVC flame-retardant copper conductor wire for house wiring and power circuits. IS 694 certified.',
            subcategory: 'Wires & Cables',
            price: 3200, originalPrice: 3600,
            materialSpecifications: 'Core: 1 | Section: 4 sq.mm | Conductor: Bare Copper | Insulation: FR PVC | IS 694 | 90 m',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Coil: 90 m. Case: 10 coils.', rating: 4.6, reviews: 290,
        },
        {
            productName: 'Polycab 1.5 sq.mm FR Wire — 90 m Coil (Yellow-Green)',
            desc: 'Single-core FR PVC insulated copper wire for earthing and light-duty circuits.',
            subcategory: 'Wires & Cables',
            price: 1150, originalPrice: 1350,
            materialSpecifications: 'Core: 1 | Section: 1.5 sq.mm | Conductor: Bare Copper | Insulation: FR PVC | IS 694 | 90 m',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Coil: 90 m. Case: 10 coils.', rating: 4.5, reviews: 215,
        },
        {
            productName: 'Havells Armoured Cable 4-Core 16 sq.mm (100 m)',
            desc: 'XLPE insulated steel-wire armoured cable for underground power distribution and industrial feeder circuits.',
            subcategory: 'Wires & Cables',
            price: 28000, originalPrice: 32000,
            materialSpecifications: 'Cores: 4 | Section: 16 sq.mm | Insulation: XLPE | Armour: SWA | Sheath: PVC | IS 7098 | 100 m',
            stock: 200, tier: 'LTL Freight Only', bulkInfo: 'Drum: 100 m. Minimum order: 1 drum.', rating: 4.6, reviews: 68,
        },
        {
            productName: 'Legrand Arteor 1-Gang 16 A Rocker Switch — White',
            desc: 'Premium modular rocker switch with anti-microbial surface. Compatible with Arteor flush plates.',
            subcategory: 'Switches',
            price: 280, originalPrice: 330,
            materialSpecifications: 'Rating: 16 A | Voltage: 240 V | Mechanism: Rocker | Color: White | IS 3854',
            stock: 10000, tier: 'Standard Export', bulkInfo: 'Case: 50 units.', rating: 4.5, reviews: 420,
        },
        {
            productName: 'Anchor Roma 2-Gang 2-Way Switch 6 A — White (Pack of 10)',
            desc: 'ISI-marked 2-way modular rocker switch for staircase lighting control in standard switch plates.',
            subcategory: 'Switches',
            price: 580, originalPrice: 680,
            materialSpecifications: 'Rating: 6 A | Poles: 2-way | Voltage: 240 V | Color: White | IS 3854 | Pack: 10',
            stock: 8000, tier: 'Standard Export', bulkInfo: 'Case: 20 packs.', rating: 4.3, reviews: 312,
        },
        {
            productName: 'Anchor 6 A 3-Pin Socket — Classic White (Pack of 10)',
            desc: 'Flush-mount 6 A 3-pin socket for general appliances. ISI-marked, fits standard modular frames.',
            subcategory: 'Sockets',
            price: 680, originalPrice: 800,
            materialSpecifications: 'Rating: 6 A | Pins: 3 | Voltage: 240 V | Color: White | IS 1293 | Pack: 10',
            stock: 8000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.3, reviews: 378,
        },
        {
            productName: 'Legrand Arteor 20 A Universal Socket — White',
            desc: 'High-current modular socket for air conditioners, geysers, and heavy appliances. Shutter-protected.',
            subcategory: 'Sockets',
            price: 520, originalPrice: 610,
            materialSpecifications: 'Rating: 20 A | Pins: Universal 3-pin | Shutter: Yes | Voltage: 240 V | IS 1293',
            stock: 5000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.5, reviews: 187,
        },
        {
            productName: 'Havells 8-Way TPN MCB Distribution Board',
            desc: 'Three-phase and neutral MCB distribution board for residential and commercial panels. IP42 enclosure.',
            subcategory: 'Distribution Boards',
            price: 3800, originalPrice: 4300,
            materialSpecifications: 'Ways: 8 | Type: TPN | Enclosure: IP42 | Bus Bar: Copper | IS 8623',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Minimum order: 3 units.', rating: 4.5, reviews: 163,
        },
        {
            productName: 'Schneider iC60N 32 A 2-Pole MCB — Type C',
            desc: 'High-performance miniature circuit breaker for domestic and commercial protection. 6 kA breaking capacity.',
            subcategory: 'Circuit Breakers',
            price: 580, originalPrice: 660,
            materialSpecifications: 'Rating: 32 A | Poles: 2 | Curve: C | Breaking Capacity: 6 kA | IS 60898-1',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.6, reviews: 234,
        },
        {
            productName: 'ABB F200 25 A 2-Pole RCCB — 30 mA',
            desc: 'Residual current circuit breaker for earth leakage protection in residential panels. Trips at 30 mA.',
            subcategory: 'Circuit Breakers',
            price: 1850, originalPrice: 2200,
            materialSpecifications: 'Rating: 25 A | Poles: 2 | Sensitivity: 30 mA | Breaking: 10 kA | IS 61008-1',
            stock: 1000, tier: 'Standard Export', bulkInfo: 'Case: 10 units.', rating: 4.6, reviews: 145,
        },
        {
            productName: 'Havells Crabtree Fan Speed Regulator — 1–5 Steps (White)',
            desc: 'Modular step-type fan speed regulator for ceiling fans. Energy-efficient with noiseless operation.',
            subcategory: 'Regulators',
            price: 180, originalPrice: 220,
            materialSpecifications: 'Steps: 5 | Rating: 100 W | Voltage: 240 V | Type: Step | Color: White | IS 3854',
            stock: 6000, tier: 'Standard Export', bulkInfo: 'Case: 50 units.', rating: 4.4, reviews: 286,
        },
    ],

    'Lighting & Fans': [
        {
            productName: 'Philips Meson 12 W LED Downlight — Warm White',
            desc: 'Recessed LED downlight for false ceiling applications. Flicker-free with long lifespan.',
            subcategory: 'Downlights',
            price: 380, originalPrice: 450,
            materialSpecifications: 'Power: 12 W | Lumens: 1050 lm | CCT: 3000 K | CRI: >80 | Cutout: 115 mm | IP20',
            stock: 5000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.6, reviews: 520,
        },
        {
            productName: 'Havells 18 W LED Slim Downlight — Cool White',
            desc: 'Ultra-slim recessed LED panel downlight with driver included. Suitable for commercial false ceilings.',
            subcategory: 'Downlights',
            price: 580, originalPrice: 680,
            materialSpecifications: 'Power: 18 W | Lumens: 1600 lm | CCT: 6500 K | CRI: >80 | Cutout: 150 mm | IP20',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.5, reviews: 312,
        },
        {
            productName: 'Polycab 12 W COB LED Spotlight — Neutral White GU10',
            desc: 'Chip-on-board LED spotlight for retail accent lighting. High CRI for accurate colour rendering.',
            subcategory: 'COB Lights',
            price: 420, originalPrice: 500,
            materialSpecifications: 'Power: 12 W | Lumens: 960 lm | CCT: 4000 K | CRI: >90 | Beam: 24° | GU10',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.5, reviews: 178,
        },
        {
            productName: 'Wipro Garnet LED Strip Light — 5 m Reel (Warm White)',
            desc: 'Flexible SMD 5050 LED strip for under-cabinet, cove, and accent lighting. Cuttable every 50 mm.',
            subcategory: 'Strip Lights',
            price: 680, originalPrice: 800,
            materialSpecifications: 'Length: 5 m | LEDs: 60/m | Power: 14.4 W/m | CCT: 3000 K | IP20 | Input: 12 V DC',
            stock: 2000, tier: 'Standard Export', bulkInfo: 'Includes 12 V 5 A driver.', rating: 4.4, reviews: 243,
        },
        {
            productName: 'Syska 24 W LED Surface Panel Light — Square Cool White',
            desc: 'Flush-mount LED panel light for office, retail, and home ceilings. Uniform illumination with slim profile.',
            subcategory: 'Surface Lights',
            price: 780, originalPrice: 920,
            materialSpecifications: 'Power: 24 W | Lumens: 2000 lm | CCT: 6500 K | Size: 300×300 mm | Depth: 15 mm | IP20',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 10 units.', rating: 4.5, reviews: 198,
        },
        {
            productName: 'Wipro 20 W LED Batten 4 ft — Cool Daylight',
            desc: 'Surface-mounted LED batten for warehouses and corridors. High lumen output with instant-on.',
            subcategory: 'Tube Lights',
            price: 480, originalPrice: 560,
            materialSpecifications: 'Power: 20 W | Lumens: 2000 lm | CCT: 6500 K | Length: 1.2 m | IP20 | IS 16102',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.4, reviews: 293,
        },
        {
            productName: 'Philips 18 W LED T8 Tube — Cool Daylight (Pack of 10)',
            desc: 'Direct-drive LED replacement tube for G13 fluorescent fittings. No starter or ballast required.',
            subcategory: 'Tube Lights',
            price: 1800, originalPrice: 2200,
            materialSpecifications: 'Power: 18 W | Lumens: 1800 lm | CCT: 6500 K | Length: 1.2 m | Base: G13 | Pack: 10',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.5, reviews: 347,
        },
        {
            productName: 'Havells Leganza 1200 mm BLDC Ceiling Fan — Pearl White',
            desc: 'BLDC ceiling fan with remote control. 5-star BEE rated, 28 W power, 5-speed regulation.',
            subcategory: 'Ceiling Fans',
            price: 4800, originalPrice: 5500,
            materialSpecifications: 'Sweep: 1200 mm | Power: 28 W | Air Delivery: 270 CMM | Speed: 5 | Star: 5 | BEE',
            stock: 800, tier: 'Standard Export', bulkInfo: 'Includes remote control.', rating: 4.7, reviews: 315,
        },
        {
            productName: 'Usha Aerostyle 1200 mm Ceiling Fan — Matt Brown',
            desc: 'Decorative ceiling fan with aerodynamic blades. Energy-efficient motor with ball bearings for quiet operation.',
            subcategory: 'Ceiling Fans',
            price: 2200, originalPrice: 2700,
            materialSpecifications: 'Sweep: 1200 mm | Power: 72 W | Air Delivery: 220 CMM | Speed: 5 | Star: 3 | IS 374',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Includes canopy and down rod.', rating: 4.4, reviews: 218,
        },
        {
            productName: 'Crompton 250 mm Anti-Dust Exhaust Fan',
            desc: 'Exhaust fan with anti-dust shutter and high air throw for bathrooms and kitchens.',
            subcategory: 'Exhaust Fans',
            price: 1100, originalPrice: 1300,
            materialSpecifications: 'Blade: 250 mm | CFM: 910 | Noise: 42 dB | Shutter: Auto | IP44 | IS 6680',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Case: 10 units.', rating: 4.4, reviews: 247,
        },
        {
            productName: 'Havells Ventil-Air 300 mm Exhaust Fan — White',
            desc: 'High-speed exhaust fan with aluminium blades and built-in shutter. Suitable for large kitchens and halls.',
            subcategory: 'Exhaust Fans',
            price: 1550, originalPrice: 1800,
            materialSpecifications: 'Blade: 300 mm | CFM: 1250 | Noise: 48 dB | Shutter: Spring-loaded | IP20 | IS 6680',
            stock: 1000, tier: 'Standard Export', bulkInfo: 'Case: 10 units.', rating: 4.3, reviews: 163,
        },
    ],

    'Electrical Infrastructure': [
        {
            productName: 'Precision 25 mm ISI UPVC Conduit Pipe — 3 m (Pack of 10)',
            desc: 'Rigid UPVC electrical conduit for concealed wiring in RCC slabs and masonry walls. Flame-retardant.',
            subcategory: 'Conduit Pipes',
            price: 1200, originalPrice: 1400,
            materialSpecifications: 'OD: 25 mm | Length: 3 m | Material: UPVC | Flame Retardant: Yes | IS 9537 Part 3 | Pack: 10',
            stock: 5000, tier: 'Bulk Distribution', bulkInfo: 'Bundle: 10 pipes.', rating: 4.3, reviews: 175,
        },
        {
            productName: 'Precision 20 mm ISI UPVC Conduit Pipe — 3 m (Pack of 10)',
            desc: 'Rigid UPVC conduit for light-duty concealed wiring. Suitable for 2.5 sq.mm wire installations.',
            subcategory: 'Conduit Pipes',
            price: 950, originalPrice: 1100,
            materialSpecifications: 'OD: 20 mm | Length: 3 m | Material: UPVC | Flame Retardant: Yes | IS 9537 Part 3 | Pack: 10',
            stock: 6000, tier: 'Bulk Distribution', bulkInfo: 'Bundle: 10 pipes.', rating: 4.3, reviews: 142,
        },
        {
            productName: 'Flexi Conduit 25 mm — 10 m (Grey)',
            desc: 'Corrugated flexible UPVC conduit for machine wiring and surface installations where bending is required.',
            subcategory: 'Conduit Pipes',
            price: 680, originalPrice: 800,
            materialSpecifications: 'OD: 25 mm | Length: 10 m | Material: UPVC | IP40 | Temp Range: -5 to +60°C | IS 9537',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Minimum order: 5 units.', rating: 4.2, reviews: 95,
        },
        {
            productName: 'ISI UPVC Conduit Fittings Set — 25 mm (Pack of 50)',
            desc: 'Assorted UPVC conduit fittings: bends, couplers, and saddle clips for 25 mm installations.',
            subcategory: 'Conduit Fittings',
            price: 650, originalPrice: 780,
            materialSpecifications: 'Size: 25 mm | Includes: 20 bends, 20 couplers, 10 saddles | Material: UPVC | IS 9537',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Case: 20 packs.', rating: 4.3, reviews: 142,
        },
        {
            productName: 'PVC Casing & Capping 25×12 mm — 3 m (Pack of 10)',
            desc: 'PVC cable management casing and capping for neat surface wiring on walls and ceilings.',
            subcategory: 'Casing & Capping',
            price: 580, originalPrice: 680,
            materialSpecifications: 'Size: 25×12 mm | Length: 3 m per piece | Material: PVC | Color: White | IS 3480 | Pack: 10',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Bundle: 10 pieces.', rating: 4.2, reviews: 118,
        },
        {
            productName: 'PVC Casing & Capping 40×20 mm — 3 m (Pack of 10)',
            desc: 'Heavy-duty PVC casing and capping for multiple-cable surface wiring runs in offices and commercial spaces.',
            subcategory: 'Casing & Capping',
            price: 820, originalPrice: 950,
            materialSpecifications: 'Size: 40×20 mm | Length: 3 m per piece | Material: PVC | Color: White | IS 3480 | Pack: 10',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Bundle: 10 pieces.', rating: 4.2, reviews: 87,
        },
        {
            productName: 'Legrand 4-Module Flush Junction Box — White',
            desc: 'Flush-mounted modular junction box for Legrand and compatible switch plates in masonry walls.',
            subcategory: 'Junction Boxes',
            price: 140, originalPrice: 165,
            materialSpecifications: 'Modules: 4 | Material: Polycarbonate | Type: Flush | Depth: 43 mm | Color: White',
            stock: 8000, tier: 'Standard Export', bulkInfo: 'Case: 50 units.', rating: 4.4, reviews: 310,
        },
        {
            productName: 'GI Back Box 4×4 inch 35 mm Deep — Powder Coated',
            desc: 'Galvanised iron back box for surface or flush mounting of distribution boards and large switch plates.',
            subcategory: 'GI Boxes',
            price: 280, originalPrice: 320,
            materialSpecifications: 'Size: 4×4 inch | Depth: 35 mm | Material: GI 1.2 mm | Finish: Powder Coated | IS 5133',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 25 units.', rating: 4.2, reviews: 98,
        },
        {
            productName: 'GI Perforated Cable Tray 100×50 mm — 3 m',
            desc: 'Galvanised perforated cable tray for organised cable management in industrial electrical installations.',
            subcategory: 'Cable Accessories',
            price: 980, originalPrice: 1150,
            materialSpecifications: 'Width: 100 mm | Depth: 50 mm | Length: 3 m | GI 1.6 mm | Load: 60 kg/m | IS 9537',
            stock: 1000, tier: 'Bulk Distribution', bulkInfo: 'Bundle: 5 pieces.', rating: 4.3, reviews: 87,
        },
        {
            productName: 'Nylon Cable Tie 300 mm×3.5 mm (Pack of 100)',
            desc: 'Standard nylon cable ties for bundling and organising cables. Self-locking, UV-stabilised.',
            subcategory: 'Cable Accessories',
            price: 180, originalPrice: 220,
            materialSpecifications: 'Length: 300 mm | Width: 3.5 mm | Material: Nylon PA 66 | Tensile: 18 kg | UV Stabilised | Pack: 100',
            stock: 10000, tier: 'Bulk Distribution', bulkInfo: 'Case: 20 packs.', rating: 4.4, reviews: 254,
        },
        {
            productName: 'Steel Back Box 2-Module Surface 1-Gang — 35 mm Deep',
            desc: 'Mild steel surface back box for single-gang modular plates. Pre-drilled, galvanised finish.',
            subcategory: 'Back Boxes',
            price: 95, originalPrice: 115,
            materialSpecifications: 'Modules: 2 | Type: Surface | Depth: 35 mm | Material: MS Galvanised | IS 5133',
            stock: 6000, tier: 'Standard Export', bulkInfo: 'Case: 50 units.', rating: 4.2, reviews: 136,
        },
    ],

    'Plumbing': [
        {
            productName: 'Astral CPVC Pipe 25 mm SDR-11 — 3 m',
            desc: 'Chlorinated PVC hot & cold water pipe for residential plumbing. Rated for 93°C continuous service.',
            subcategory: 'CPVC Pipes',
            price: 380, originalPrice: 440,
            materialSpecifications: 'OD: 33.4 mm | SDR: 11 | Service Temp: 93°C | Pressure: 150 psi | ASTM D2846',
            stock: 6000, tier: 'Standard Export', bulkInfo: 'Bundle: 10 pipes.', rating: 4.5, reviews: 290,
        },
        {
            productName: 'Astral CPVC Pipe 40 mm SDR-11 — 3 m',
            desc: 'CPVC hot & cold water pipe for riser mains and branch distribution in multi-storey buildings.',
            subcategory: 'CPVC Pipes',
            price: 860, originalPrice: 980,
            materialSpecifications: 'OD: 48.3 mm | SDR: 11 | Service Temp: 93°C | Pressure: 150 psi | ASTM D2846',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Bundle: 10 pipes.', rating: 4.4, reviews: 135,
        },
        {
            productName: 'Astral CPVC Elbow 25 mm 90° — Pack of 10',
            desc: 'Solvent-weld CPVC 90° elbow fitting for hot & cold water supply lines.',
            subcategory: 'Pipe Fittings',
            price: 280, originalPrice: 330,
            materialSpecifications: 'Size: 25 mm | Angle: 90° | Material: CPVC | Joint: Solvent Weld | Temp: up to 93°C | Pack: 10',
            stock: 5000, tier: 'Standard Export', bulkInfo: 'Case: 20 packs.', rating: 4.5, reviews: 203,
        },
        {
            productName: 'Astral CPVC Ball Valve 25 mm — Full Bore',
            desc: 'Full-bore CPVC ball valve for hot & cold water shut-off in residential plumbing systems.',
            subcategory: 'Pipe Fittings',
            price: 380, originalPrice: 440,
            materialSpecifications: 'Size: 25 mm | Material: CPVC | Ball: PTFE Seats | Temp: up to 93°C | Pressure: 150 psi',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 20 units.', rating: 4.4, reviews: 162,
        },
        {
            productName: 'Supreme UPVC Column Pipe 110 mm PN-10 — 6 m',
            desc: 'UPVC column pipe for submersible pumps and borewell applications. UV-stabilised.',
            subcategory: 'UPVC Pipes',
            price: 2600, originalPrice: 2950,
            materialSpecifications: 'OD: 110 mm | Pressure: PN-10 | Length: 6 m | UV Stabilised | IS 4985',
            stock: 1500, tier: 'Standard Export', bulkInfo: 'Bundle: 5 pipes.', rating: 4.4, reviews: 143,
        },
        {
            productName: 'Zoloto Brass Ball Valve 25 mm PN20 — Full Bore',
            desc: 'Full-bore brass ball valve for water supply and HVAC shut-off. Quarter-turn operation.',
            subcategory: 'Valves',
            price: 320, originalPrice: 380,
            materialSpecifications: 'Size: 25 mm | Body: Brass | Ball: Chrome-plated | BSP Thread | PN: 20 | IS 9890',
            stock: 4000, tier: 'Standard Export', bulkInfo: 'Case: 25 units.', rating: 4.4, reviews: 183,
        },
        {
            productName: 'Leader Float Valve 25 mm — Plastic Body (Pack of 5)',
            desc: 'Plastic float valve for overhead tanks and cisterns. Side entry, stainless steel shaft.',
            subcategory: 'Valves',
            price: 420, originalPrice: 500,
            materialSpecifications: 'Size: 25 mm | Body: Engineering Plastic | Shaft: SS | Type: Side Entry | Pack: 5',
            stock: 2500, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.2, reviews: 128,
        },
        {
            productName: 'Sintex FRP Triple-Layer Water Tank — 1000 L',
            desc: 'Layered FRP water storage tank with UV-stabilised outer layer and food-grade inner. BIS certified.',
            subcategory: 'Water Tanks',
            price: 5800, originalPrice: 6500,
            materialSpecifications: 'Capacity: 1000 L | Layers: 3 | Outer: UV Black | Inner: Food Grade | IS 12701 | Warranty: 5 yr',
            stock: 400, tier: 'LTL Freight Only', bulkInfo: 'Delivery within 50 km.', rating: 4.5, reviews: 218,
        },
        {
            productName: 'Sintex FRP Water Tank — 500 L (Double Layer)',
            desc: 'Compact double-layer FRP water tank for residential rooftop use. Lightweight and easy to install.',
            subcategory: 'Water Tanks',
            price: 3200, originalPrice: 3700,
            materialSpecifications: 'Capacity: 500 L | Layers: 2 | UV Stabilised | Food Grade Inner | IS 12701',
            stock: 600, tier: 'LTL Freight Only', bulkInfo: 'Delivery within 50 km.', rating: 4.4, reviews: 178,
        },
        {
            productName: 'Ashirvad UPVC SWR Pipe 110 mm — 3 m (Rubber Ring Joint)',
            desc: 'Soil, waste, and rainwater UPVC drainage pipe. Rubber ring push-fit joint for leak-proof installation.',
            subcategory: 'Drainage Systems',
            price: 680, originalPrice: 780,
            materialSpecifications: 'OD: 110 mm | Length: 3 m | Type: SWR | Joint: Rubber Ring | IS 13592',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Bundle: 10 pipes.', rating: 4.3, reviews: 165,
        },
        {
            productName: 'Supreme Underground PVC Drainage Pipe 160 mm — 6 m',
            desc: 'Rigid PVC pipe for underground sewer and stormwater drainage. Smooth inner bore for self-cleansing flow.',
            subcategory: 'Drainage Systems',
            price: 2800, originalPrice: 3200,
            materialSpecifications: 'OD: 160 mm | Length: 6 m | Stiffness: SN4 | Joint: Rubber Ring | IS 15328',
            stock: 800, tier: 'Standard Export', bulkInfo: 'Bundle: 5 pipes.', rating: 4.4, reviews: 92,
        },
    ],

    'Sanitary & Bath': [
        {
            productName: 'Jaquar Kubix Prime Single-Lever Basin Faucet — Chrome',
            desc: 'Single-lever hot & cold basin mixer with ceramic disc cartridge for drip-free operation. 10-year warranty.',
            subcategory: 'Faucets & Taps',
            price: 3800, originalPrice: 4400,
            materialSpecifications: 'Body: Brass | Finish: Chrome | Cartridge: Ceramic 35 mm | Flow: 8 L/min | Warranty: 10 yr',
            stock: 800, tier: 'Standard Export', bulkInfo: 'Includes aerator and flexible hoses.', rating: 4.6, reviews: 230,
        },
        {
            productName: 'Grohe Eurosmart Kitchen Sink Mixer — Pull-Out Spray',
            desc: 'Kitchen sink mixer with pull-out spray head. Two-function spray/stream mode. SilkMove ceramic cartridge.',
            subcategory: 'Faucets & Taps',
            price: 7800, originalPrice: 9000,
            materialSpecifications: 'Body: Brass | Finish: Chrome | Hose: 1.75 m | Flow: 6 L/min | Spray: 2 functions | IS 8931',
            stock: 300, tier: 'Standard Export', bulkInfo: 'Includes mounting hardware.', rating: 4.7, reviews: 97,
        },
        {
            productName: 'Jaquar Kubix Plus Pillar Cock — Chrome',
            desc: 'Quarter-turn ceramic disc pillar cock for washbasins and kitchen sinks. Drip-free, easy installation.',
            subcategory: 'Faucets & Taps',
            price: 1650, originalPrice: 1900,
            materialSpecifications: 'Body: Brass | Finish: Chrome | Cartridge: Ceramic | Flow: 10 L/min | IS 8931',
            stock: 1200, tier: 'Standard Export', bulkInfo: 'Case: 10 units.', rating: 4.4, reviews: 168,
        },
        {
            productName: 'Hindware Quartz Wall-Hung WC — Rimless P-Trap',
            desc: 'Rimless wall-hung toilet with nano glaze coating. Hygienic and easy-to-clean design.',
            subcategory: 'Sanitary Ware',
            price: 12500, originalPrice: 14500,
            materialSpecifications: 'Type: Wall-Hung | Design: Rimless | Trap: P-trap 180 mm | Flush: 4.5/3 L dual | IS 2556',
            stock: 300, tier: 'Standard Export', bulkInfo: 'Includes seat cover. Cistern sold separately.', rating: 4.5, reviews: 135,
        },
        {
            productName: 'Cera Lyra One-Piece Water Closet — White',
            desc: 'One-piece siphonic WC with slow-close seat. Integrated cistern, easy cleaning, compact footprint.',
            subcategory: 'Sanitary Ware',
            price: 9800, originalPrice: 11500,
            materialSpecifications: 'Type: One-piece | Trap: S-trap 180 mm | Flush: 6/3 L dual | Material: Vitreous China | IS 2556',
            stock: 200, tier: 'Standard Export', bulkInfo: 'Includes slow-close seat cover.', rating: 4.5, reviews: 108,
        },
        {
            productName: 'Jaquar Continental Wall-Hung Wash Basin — White',
            desc: 'Vitreous china wall-hung washbasin with integrated towel rail. Compact for modern bathrooms.',
            subcategory: 'Sanitary Ware',
            price: 4200, originalPrice: 4800,
            materialSpecifications: 'Material: Vitreous China | Size: 560×400 mm | Type: Wall-Hung | IS 2556 Part 4',
            stock: 500, tier: 'Standard Export', bulkInfo: 'Includes waste coupling.', rating: 4.4, reviews: 98,
        },
        {
            productName: 'Parryware Aria Pedestal Wash Basin — White',
            desc: 'Classic pedestal washbasin with full-pedestal. Overflow and waste fitting included.',
            subcategory: 'Sanitary Ware',
            price: 5500, originalPrice: 6200,
            materialSpecifications: 'Material: Vitreous China | Basin Size: 575×455 mm | Type: Full Pedestal | IS 2556 Part 4',
            stock: 400, tier: 'Standard Export', bulkInfo: 'Includes pedestal, basin, and waste fitting.', rating: 4.3, reviews: 124,
        },
        {
            productName: 'Cera Alto 5-Function Overhead Shower Set — Chrome',
            desc: 'Rain shower with 5-function handheld, slide bar, and wall arm. Complete luxury shower set.',
            subcategory: 'Bathroom Fittings',
            price: 8900, originalPrice: 10500,
            materialSpecifications: 'Rain Shower: 250 mm | Handheld: 5-function | Hose: 1.5 m | Body: Brass | Finish: Chrome',
            stock: 350, tier: 'Standard Export', bulkInfo: 'Complete set with all hardware.', rating: 4.6, reviews: 112,
        },
        {
            productName: 'Hindware Squareline 5-Piece Bathroom Accessory Set — SS',
            desc: 'Coordinated bathroom accessory set: towel ring, toilet paper holder, robe hook, towel bar, and soap dish.',
            subcategory: 'Bathroom Fittings',
            price: 3200, originalPrice: 3800,
            materialSpecifications: 'Material: SS 304 | Finish: Brushed Nickel | Pieces: 5 | Wall-mounted | Includes screws and anchors',
            stock: 600, tier: 'Standard Export', bulkInfo: 'Complete 5-piece set.', rating: 4.5, reviews: 183,
        },
        {
            productName: 'Jayna Stainless Steel Floor Drain — 5 inch (Pack of 4)',
            desc: 'Anti-odour floor drain with removable strainer and water-seal trap. For bathrooms, balconies, and utility areas.',
            subcategory: 'Bathroom Fittings',
            price: 680, originalPrice: 800,
            materialSpecifications: 'Size: 5 inch (127 mm) | Material: SS 304 | Trap: Water Seal | Strainer: Removable | Pack: 4',
            stock: 3000, tier: 'Standard Export', bulkInfo: 'Case: 10 packs.', rating: 4.4, reviews: 215,
        },
        {
            productName: 'Roca Senso Concealed Cistern — 6/3 L Dual Flush',
            desc: 'In-wall concealed cistern for wall-hung WC. Dual-flush 6/3 L with chrome flush plate.',
            subcategory: 'Sanitary Ware',
            price: 14500, originalPrice: 16800,
            materialSpecifications: 'Flush: 6/3 L dual | Frame: Steel | Cistern: PP | Depth: 120 mm | Flush Plate: Chrome | IS 7231',
            stock: 150, tier: 'Custom Fab', bulkInfo: 'Includes in-wall frame, cistern, and chrome flush plate.', rating: 4.6, reviews: 67,
        },
    ],
};

// ─────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────

async function seed() {
    const MONGO_URI = process.env.MONGO_URI;
    if (!MONGO_URI) {
        console.error('MONGO_URI not found in env file');
        process.exit(1);
    }

    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB\n');

    const categories = await Category.find({});
    const catMap = {};
    categories.forEach(c => { catMap[c.name] = c._id; });

    let inserted = 0;
    let updated  = 0;
    let skipped  = 0;

    for (const [catName, products] of Object.entries(PRODUCTS_BY_CATEGORY)) {
        const catId = catMap[catName];
        if (!catId) {
            console.warn(`  SKIP (category not found) — "${catName}"`);
            skipped += products.length;
            continue;
        }

        console.log(`\n── ${catName} (${products.length} products)`);
        for (const p of products) {
            const existing = await Product.findOne({ productName: p.productName });
            if (existing) {
                Object.assign(existing, { ...p, category: catId });
                await existing.save();
                console.log(`   UPDATE — ${p.productName}`);
                updated++;
            } else {
                await Product.create({ ...p, category: catId });
                console.log(`   INSERT — ${p.productName}`);
                inserted++;
            }
        }
    }

    console.log('\n─────────────────────────────────');
    console.log(`  Inserted : ${inserted}`);
    console.log(`  Updated  : ${updated}`);
    if (skipped) console.log(`  Skipped  : ${skipped} (missing categories)`);
    console.log(`  Total    : ${inserted + updated}`);
    console.log('─────────────────────────────────');

    await mongoose.disconnect();
    process.exit(0);
}

seed().catch((err) => {
    console.error('Product seed failed:', err);
    mongoose.disconnect();
    process.exit(1);
});
